Models/ErrorViewModel.cs
using System;

namespace PortalUniversitario.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Unidade.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PortalUniversitario.Models
{
    public class Unidade
    {
        public int IdUnidade { get; set; }

        [Display(Name = "Nome")]
        [Required(ErrorMessage = "Campo nome obrigatório")]
        public string Nome { get; set; }

        public string Endereco { get; set; }

        public string Telefone { get; set; }

        public string CNPJ { get; set; }

        public string Site { get; set; }

        public int IdUniv { get; set; }

        public string Universidade { get; set; }

        public string Img { get; set; }
    }
}

Models/Universidade.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PortalUniversitario.Models
{
    public class Universidade
    {
        public int? IdUniversidade { get; set; }
        
        [Display(Name="Nome")]
        [Required(ErrorMessage ="Campo nome obrigatório")]
        public string Nome { get; set; }

        public string Img { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PortalUniversitario.Models;

namespace PortalUniversitario.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UnidadeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PortalUniversitario.Models;
using PortalUniversitario.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PortalUniversitario.Controllers
{
    public class UnidadeController : Controller
    {
        public IActionResult Index()
        {
            using (var data = new UnidadeData())
                return View(data.Read());
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Unidade e)
        {
            if (!ModelState.IsValid)
            {
                return View(e);
            }

            using (var data = new UnidadeData())
                data.Create(e);

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            using (var data = new UnidadeData())
                data.Delete(id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            using (var data = new UnidadeData())
                return View(data.Read(id));
        }

        [HttpPost]
        public IActionResult Update(int id, Unidade e)
        {
            e.IdUnidade = id;

            if (!ModelState.IsValid)
                return View(e);

            using (var data = new UnidadeData())
                data.Update(e);

            return RedirectToAction("Index");
        }



    }
}

Controllers/UniversidadeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PortalUniversitario.Models;
using PortalUniversitario.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PortalUniversitario.Controllers
{
    public class UniversidadeController : Controller
    {
        public IActionResult Index()
        {
            using (var data = new UniversidadeData())
                return View(data.Read());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create (Universidade e)
        {
            if (!ModelState.IsValid)
            {
                return View(e);
            }

            using (var data = new UniversidadeData())
                data.Create(e);

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            using (var data = new UniversidadeData())
                data.Delete(id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            using (var data = new UniversidadeData())
                return View(data.Read(id));
        }

        [HttpPost]
        public IActionResult Update(int id, Universidade e)
        {
            e.IdUniversidade = id;

            if (!ModelState.IsValid)
                return View(e);

            using (var data = new UniversidadeData())
                data.Update(e);

            return RedirectToAction("Index");
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Produto/Index.cshtml
@model List<Universidade>

<table class="table table-hover">

    @foreach (var u in Model)
    {
    <tr>
        <td>@u.IdUniversidade</td>
        <td>@u.Nome</td>
        <td>@u.Img</td>
        <td>
            <a class="btn btn-sm btn-danger" href="/universidade/delete/@u.IdUniversidade">Apagar</a>
            <a class="btn btn-sm btn-warning" href="/universidade/update/@u.IdUniversidade">Editar</a>
        </td>
    </tr>
    }

</table>

<a class="btn btn-primary" href="/universidade/create">Adicionar</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PortalUniversitario</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PortalUniversitario</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - PortalUniversitario - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Unidade/Create.cshtml
@model Unidade

    <form asp-controller="Unidade" asp-action="Create" method="post">

        <div class="form-group">
            <label asp-for="Nome"></label>
            <input asp-for="Nome" class="form-control" />
            <span asp-validation-for="Nome"></span>
        </div>

        <div class="form-group">
            <label asp-for="Endereco"></label>
            <input asp-for="Endereco" class="form-control" />
            <span asp-validation-for="Endereco"></span>
        </div>

        <div class="form-group">
            <label asp-for="Telefone"></label>
            <input asp-for="Telefone" class="form-control" />
            <span asp-validation-for="Telefone"></span>
        </div>

        <div class="form-group">
            <label asp-for="CNPJ"></label>
            <input asp-for="CNPJ" class="form-control" />
            <span asp-validation-for="CNPJ"></span>
        </div>

        <div class="form-group">
            <label asp-for="Site"></label>
            <input asp-for="Site" class="form-control" />
            <span asp-validation-for="Site"></span>
        </div>

        <div class="form-group">
            <label asp-for="IdUniv"></label>
            <input asp-for="IdUniv" class="form-control" />
            <span asp-validation-for="IdUniv"></span>
        </div>


        <button class="btn btn-primary">Salvar</button>
    </form>

Views/Unidade/Index.cshtml
@model List<Unidade>

<table class="table table-hover">

    @foreach (var u in Model)
    {
    <tr>
        <td>@u.IdUnidade</td>
        <td>@u.Nome</td>
        <td>@u.Endereco</td>
        <td>@u.Telefone</td>
        <td>@u.CNPJ</td>
        <td>@u.Site</td>
        <td>
            <a class="btn btn-sm btn-danger" href="/unidade/delete/@u.IdUnidade">Apagar</a>
            <a class="btn btn-sm btn-warning" href="/unidade/update/@u.IdUnidade">Editar</a>
        </td>
    </tr>
    }

</table>

<a class="btn btn-primary" href="/unidade/create">Adicionar</a>

Views/Unidade/Update.cshtml
@model Unidade

    <form asp-controller="Unidade" asp-action="Update" method="post">

        <div class="form-group">
            <label asp-for="Nome"></label>
            <input asp-for="Nome" class="form-control" />
            <span asp-validation-for="Nome"></span>
        </div>

        <div class="form-group">
            <label asp-for="Endereco"></label>
            <input asp-for="Endereco" class="form-control" />
            <span asp-validation-for="Endereco"></span>
        </div>

        <div class="form-group">
            <label asp-for="Telefone"></label>
            <input asp-for="Telefone" class="form-control" />
            <span asp-validation-for="Telefone"></span>
        </div>

        <div class="form-group">
            <label asp-for="CNPJ"></label>
            <input asp-for="CNPJ" class="form-control" />
            <span asp-validation-for="CNPJ"></span>
        </div>

        <div class="form-group">
            <label asp-for="Site"></label>
            <input asp-for="Site" class="form-control" />
            <span asp-validation-for="Site"></span>
        </div>

        <div class="form-group">
            <label asp-for="IdUniv"></label>
            <input asp-for="IdUniv" class="form-control" />
            <span asp-validation-for="IdUniv"></span>
        </div>

        <button class="btn btn-primary">Salvar</button>

    </form>

Views/Universidade/Create.cshtml
@model Universidade

    <form asp-controller="Universidade" asp-action="Create" method="post">

        <div class="form-group">
            <label asp-for="Nome"></label>
            <input asp-for="Nome" class="form-control" />
            <span asp-validation-for="Nome"></span>
        </div>

        <div class="form-group">
            <label asp-for="Img">Imagem</label>
            <input asp-for="Img" class="form-control" />
            <span asp-validation-for="Img"></span>
        </div>

        <button class="btn btn-primary">Salvar</button>
    </form>

Views/Universidade/Index.cshtml
@model List<Universidade>

<table class="table table-hover">

    @foreach (var u in Model)
    {
        <tr>
            <td>@u.IdUniversidade</td>
            <td>@u.Nome</td>
            <td>@u.Img</td>
            <td>
                <a class="btn btn-sm btn-danger" href="/universidade/delete/@u.IdUniversidade">Apagar</a>
                <a class="btn btn-sm btn-warning" href="/universidade/update/@u.IdUniversidade">Editar</a>
            </td>
        </tr>
    }

</table>

<a class="btn btn-primary" href="/universidade/create">Adicionar</a>

Views/Universidade/Update.cshtml
@model Universidade

    <form asp-controller="Universidade" asp-action="Update" method="post">

        <div class="form-group">
            <label asp-for="Nome"></label>
            <input asp-for="Nome" class="form-control" />
            <span asp-validation-for="Nome"></span>
        </div>

        <div class="form-group">
            <label asp-for="Img"></label>
            <input asp-for="Img" class="form-control" />
            <span asp-validation-for="Img"></span>
        </div>

        <button class="btn btn-primary">Salvar</button>

    </form>